### PR TITLE
Introduces CPEIN functionalities into cphstats and cestats

### PR DESCRIPTION
**Pull request by vwcruzeiro**

### CODE REVIEW

**Comment by vwcruzeiro** [comment]
@swails : I ran all the tests locally with both gcc-4.8 and gcc-5 and they all pass. I don't know why it is failing on Travis CI then.

**Comment by vwcruzeiro** [comment]
run travis

**Comment by swails** [comment]
I think @drroe subsumed cphstats functionality into cpptraj. It would probably be best to put this there instead so cphstats can be deprecated and removed.

**Comment by swails** [comment]
Also the error message is this:

Error: Could not open or parse tyx.cpein for reading!

Looks like you forgot to add this file to git.

**Comment by vwcruzeiro** [comment]
Hello @swails . @drroe did an amazing work in cpptraj and it is likely we will be able to deprecate cphstats and cestats soon. However, there is still some work to be done. I don’t remember if all cphstats have been implemented yet into cpptraj. And it is still necessary to implement cestats.

Regarding the test error message: the tyx.cpein file is in place. Please notice that the tests are executed in 4 different ways, and in 1 of them all tests pass. This failure might be compiler related, however I could not reproduce it locally in order to fix. Any suggestions?

**Comment by swails** [comment]
The test also failed on my machine.

I believe the root cause is that `logical` in Fortran does not interoperate with `bool` in C/C++ as a general rule (integers and floats/doubles do).  As a result, `is_cpin` was not being interpreted by the Fortran parsing routines the way the C++ function was passing it in.

Switching to using an integer for the internal representation of `is_cpin_` fixed the issue (at least on my machine).

That said, I'm a little nervous of the test you're using to see how it's supposed to be parsed.  You're simply assuming that the first line is *always* going to be the namelist line.  But that's not necessarily the case.  If there's a blank line (perfectly legal), then it fails to parse correctly.

**Comment by swails** [comment]
To expand on my last post -- `logical` and `bool` *can* be interchangeable, but that's best considered accidental.  So one of the tests passed previously because, in that case only, the correct value of the logical flag was passed to the Fortran routine.

**Comment by swails** [comment]
I have some general comments on the approach taken here which I should have raised when you first made cestats.  I won't hold up merging this as a result, but I think it would be useful for making possibly better decisions in the future (for instance, ParmEd made much better decisions than MMPBSA.py because I had learned from MMPBSA.py before I wrote ParmEd).

The cestats functionality should not have been implemented as an alternative code path spliced in via a flood of `#ifdef REDOX` preprocessor directives.  It should have been a separate operating mode of the same program.  Logic could have been implemented to pick the operating mode either by command-line flags used or just the content of the cpin file.

You could have achieved this using polymorphism.  The cphstats and cestats functionalities should have been implemented in separate classes that each inherit from a common base class that essentially counts states in an MD simulation from a cpout/ceout file.

A code littered with `#ifdef <SOMETHING>` to spawn multiple executables out of a single code base gets very confusing very fast, and it's far more difficult to reliably test all possible combinations.  A prime example is sander.LES.  The main reason that was done was for performance reasons (don't let LES additions degrade normal calculations) -- a concern that I don't think applies here. In any case, sander.LES *could* have been designed in a way that didn't impact performance (especially with C++).

My take-home lesson -- avoid ifdefs where possible.  If you're thinking about using them, consider alternatives that allow you not to.

**Comment by vwcruzeiro** [comment]
Hello @swails . Thank you very much for your help. I completely agree with all your comments. As I am not a C++ programmer, I hope you can imagine how tricky it was for me to make the implementations I needed in cphstats. The use of #ifdef was the easiest solution I could think in terms of coding. It would have been much harder to implement on the way you suggested, but I agree it would be the best way. Anyway, hopefully we will be able to discontinue cphstats and cestats soon, thanks to @drroe . Thank you again and happy thanksgiving.

**Pull request merged**
